POST http://localhost:1234/productos
Content-Type: application/json

{
    "nombre": "Conjunto Formal",
    "precio": 250,
    "inventario": 2,
    "descripcion": "Conjunto formal color negro, tela algodon.",
    "colores": ["Negro", "Azul Rey"],
    "categorias": ["Pantalones"],
    "tallas": ["M"]
}

###get

GET http://localhost:1234/productos

#### gatid

GET http://localhost:1234/productos/6

###update 

PATCH http://localhost:1234/productos/6
Content-Type: application/json

{
    
    "precio": 300,
    "inventario": 500,
    "descripcion": "Conjunto formal"
}

###delete
DELETE  http://localhost:1234/productos/1